version: "3.9"

services:
  stash:
    image: stashapp/stash:latest
    container_name: stash
    ports:
      - "9999:9999"
    volumes:
      - ./stash-data:/root/.stash

  stash-exporter:
    image: ghcr.io/${GITHUB_OWNER:-example}/stashapp-prometheus-exporter:latest
    container_name: stash-exporter
    environment:
      STASH_GRAPHQL_URL: http://stash:9999/graphql
      STASH_API_KEY: ${STASH_API_KEY}
      SCRAPE_INTERVAL_SECONDS: "30"
    ports:
      - "9100:9100"
    depends_on:
      - stash

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - stash-exporter

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-data:


